export const routes = {
  login: "/login",
  dashboard: "/",
  users: "/users",
  userCreate: "/users/new",
  userEdit: (id: string) => `/users/${id}/edit`,
  myProfile: "/me/profile",
  participants: "/participants",
  participantCreate: "/participants/new",
  participantDetail: (id: string) => `/participants/${id}`,
  participantEdit: (id: string) => `/participants/${id}/edit`,
  questionnaires: "/questionnaires",
  tests: "/tests",
  test2mst: "/tests/2mst",
  testSl30s: "/tests/sl30s",
  testTug: "/tests/tug",
  testUtt: "/tests/utt",
  testLos: "/tests/los",
  institutions: "/institutions",
  institutionCreate: "/institutions/new",
  institutionEdit: (id: string) => `/institutions/${id}/edit`,
  myInstitution: "/my-institution",
  myInstitutionUserCreate: "/my-institution/users/new",
  myInstitutionUserEdit: (id: string) => `/my-institution/users/${id}/edit`,
  knowledgeBase: "/knowledge-base",
};